plugins {
    // see https://fabricmc.net/develop/ for new versions
    // see https://maven.fabricmc.net/fabric-loom/fabric-loom.gradle.plugin/ for latest
    id 'net.fabricmc.fabric-loom' version '1.16.3' apply false
    // see https://projects.neoforged.net/neoforged/moddevgradle for new versions
    id 'net.neoforged.moddev' version '2.0.141' apply false
}
