# Gradle
org.gradle.jvmargs=-Xmx3G

# Project
mod_version=2.9.13.3
last_mod_version=2.9.13.2
whitenoise_version=1.20.1.6
whitenoise_range=[1.20.1,1.20.2)
java_version=17

# Common
minecraft_version=1.20.1
minecraft_short_version=1.20
mixin_version=0.8.5

# Parchment
# https://parchmentmc.org/docs/getting-started
mappings_version=2023.09.03

# Forge
# https://files.minecraftforge.net/net/minecraftforge/forge/
forge_version=47.4.8
forge_version_range=[46,)
forge_mc_version_range=[1.20,1.20.2)

# Fabric
fabric_version=0.92.6+1.20.1
fabric_mc_version_range=1.20.1
fabric_loader_version=0.16.14
fabric_loader_min_version=>=0.15
fabric_parchment_mc_version=1.20.1
# https://www.curseforge.com/minecraft/mc-mods/modmenu/files/all
mod_menu_version=7.2.2

# Other mods
jei_version=15.20.0.112
rei_version=12.1.785
spectrelib_version=0.13.15
spectrelib_range=[0.13,0.14)
architectury_version=5137938
cardinal_components_version=5.2.0
patchouli_version=1.20.1-85
patchouli_provider_version=1.20.1-1.0.9-Snapshot.4
serene_seasons_forge_version=6398227
glitchcore_forge_version=5787839
ecliptic_seasons_forge_version=6855320
simpletextoverlay_forge_version=5905892
simpletextoverlay_fabric_version=5905886
bop_forge_version=6364065
terrablender_forge_version=6290448
terrablender_fabric_version=6290449
regions_forge_version=5558225
regions_fabric_version=5558172
forge_config_fabric_version=5902421
byg_forge_version=5894931
byg_fabric_version=5894930
tyg_forge_version=5693539
tyg_fabric_version=5693538
corgilib_forge_version=5691268
corgilib_fabric_version=5691267
geckolib_forge_version=4.4.9
geckolib_fabric_version=4.4.9
create_forge_version=4835191
create_fabric_version=5245234
ars_forge_version=5600384
twilightforest_forge_version=4653704
fabric_seasons_version=4699698
sewingkit_version=1.8.0
more_food_forge_version=4756045
more_food_fabric_version=4756043
phc_food_core_forge_version=5097798
phc_crops_forge_version=4687624
phc_trees_forge_version=4625518
phc_food_extended_forge_version=5147171
crafttweaker_forge_version=5375591
kubejs_forge_version=5454840
rhino_forge_version=4944325

# Mod options
mod_name=Homeostatic
mod_id=homeostatic
mod_author=wendall911
mod_credits=ashar42
license=MIT
issue_tracker=https://github.com/wendall911/Homeostatic/issues
mod_description=A mod about body temperature and moisture. Achieving homeostasis after a little trial and error.
mod_update_branch=1.20.1

# CurseForge/Modrinth Options
release_type=release
release_versions=1.20.1
