# Gradle
org.gradle.jvmargs=-Xmx3G

# Project
version=2.9.15.0
last_mod_version=2.9.14.0
neoforge_mod_version=1.21.8-2.9.15.0-NEOFORGE
fabric_mod_version=1.21.8-2.9.15.0-FABRIC
whitenoise_version=1.21.8.1
whitenoise_range=[1.21.8,1.21.9)
java_version=21

# Common
minecraft_version=1.21.8
mixin_version=0.8.5
mixin_extras_version=0.3.5

# Parchment
# https://parchmentmc.org/docs/getting-started
mappings_version=2025.07.20

# NeoForge
# https://projects.neoforged.net/neoforged/neoforge
neoforge_version=21.8.46
neoforge_loader_version_range=[4,)
neoforge_mc_version_range=[1.21.2, 1.22)
# https://projects.neoforged.net/neoforged/neoform
neo_form_version=1.21.8-20250717.133445

# Fabric
# https://fabricmc.net/develop/
fabric_version=0.133.4+1.21.8
fabric_loader_version=0.17.2
fabric_loader_min_version=>=0.15
fabric_mc_version_range=["1.21.8","1.21.9"]
# https://www.curseforge.com/minecraft/mc-mods/modmenu/files/all
mod_menu_version=15.0.0

# Other mods
jei_version=24.0.0.2
rei_version=20.0.811
spectrelib_version=0.17.2+1.21
spectrelib_range=[0.17,0.18)
architectury_version=17.0.8
cloth_config_version=19.0.147
cardinal_components_version=7.0.0-beta.1
patchouli_version=???
patchouli_provider_version=???
serene_seasons_neoforge_version=6812965
serene_seasons_fabric_version=6812964
glitch_core_neoforge_version=6812823
glitch_core_fabric_version=6812822
simpletextoverlay_neoforge_version=???
simpletextoverlay_fabric_version=???
bop_neoforge_version=6852411
bop_fabric_version=6852410
terrablender_neoforge_version=6786184
terrablender_fabric_version=6786183
regions_neoforge_version=???
regions_fabric_version=???
forge_config_fabric_version=6782474
byg_neoforge_version=6889537
byg_fabric_version=6889534
tyg_neoforge_version=6823051
tyg_fabric_version=6823049
corgilib_neoforge_version=6822793
corgilib_fabric_version=6822789
geckolib_neoforge_version=5.2.2
geckolib_fabric_version=5.2.2
create_neoforge_version=???
create_fabric_version=???
ars_neoforge_version=???
twilightforest_forge_version=???
sewingkit_version=2.4.0
more_food_neoforge_version=6672030
more_food_fabric_version=6672027
phc_food_core_neoforge_version=???
phc_crops_neoforge_version=???
phc_trees_neoforge_version=???
phc_food_extended_neoforge_version=???
crafttweaker_neoforge_version=???
kubejs_neoforge_version=???
rhino_neoforge_version=???
colorful_hearts_neoforge_version=???
colorful_hearts_fabric_version=???
lmba_neoforge_version=6783041
lmba_fabric_version=6783040
puzzles_lib_neoforge_version=6872941
puzzles_lib_fabric_version=6872940
forge_config_api_fabric_version=6782474
vampirism_neoforge_version=???
fabric_seasons_version=???
fabric_seasons_extras_version=???
ecliptic_neoforge_version=???

# Mod options
mod_name=Homeostatic
mod_id=homeostatic
mod_author=wendall911
mod_credits=ashar42
license=MIT
issue_tracker=https://github.com/wendall911/Homeostatic/issues
mod_description=A mod about body temperature and moisture. Achieving homeostasis after a little trial and error.
mod_url=https://github.com/wendall911/Homeostatic
mod_update_branch=1.21

# CurseForge/Modrinth Options
release_type=release
release_versions=1.21.8
