# Gradle
org.gradle.jvmargs=-Xmx3G

# Project
version=2.11.0.3
last_mod_version=2.11.0.2
group=com.github.wendall911.homeostatic

# Common
minecraft_version=26.1.2
mixin_extras_version=0.5.3
whitenoise_version=2.1.0
whitenoise_range=[2.0.0,3.0.0)
fabric_whitenoise_range=[">=2.0.0","<=3.0.0"]
handbook_version=1.2.3
climatesettings_version=1.2.1
mixin_version=0.8.5
java_version=25

# NeoForge
# https://projects.neoforged.net/neoforged/neoforge
neoforge_version=26.1.2.1-beta
neoforge_loader_version_range=[4,)
neoforge_mc_version_range=[26.1, 26.2)
# https://projects.neoforged.net/neoforged/neoform
neo_form_version=26.1.2-1

# Fabric
# https://fabricmc.net/develop/
fabric_version=0.145.4+26.1.2
fabric_api_min_version=>=0.143.10
fabric_loader_version=0.18.6
fabric_loader_min_version=>=0.15
fabric_mc_version_range=[">26.1-"]
# https://www.curseforge.com/minecraft/mc-mods/modmenu/files/all
mod_menu_version=18.0.0-alpha.8

# Integration and Testing Mods
homeostaticseasons_version=1.1.0.7
# https://www.curseforge.com/minecraft/mc-mods/jei/files/all
jei_version=29.4.0.23
jei_minecraft_version=26.1.1
# https://www.curseforge.com/minecraft/mc-mods/roughly-enough-items/files/all
rei_version=21.9.812
# https://www.curseforge.com/minecraft/mc-mods/architectury-api/files/all
architectury_version=19.0.1
# https://www.curseforge.com/minecraft/mc-mods/cloth-config/files/all
cloth_config_version=26.1.154
# https://www.curseforge.com/minecraft/mc-mods/cardinal-components-api/files/all
cardinal_components_version=8.0.0-alpha.5+26.1
serene_seasons_neoforge_version=7774493
serene_seasons_fabric_version=7774492
glitch_core_neoforge_version=7835065
glitch_core_fabric_version=7835064
simpletextoverlay_neoforge_version=???
simpletextoverlay_fabric_version=???
bop_neoforge_version=
bop_fabric_version=
terrablender_neoforge_version=
terrablender_fabric_version=
regions_neoforge_version=???
regions_fabric_version=???
byg_neoforge_version=???
byg_fabric_version=???
tyg_neoforge_version=???
tyg_fabric_version=???
corgilib_neoforge_version=???
corgilib_fabric_version=???
geckolib_neoforge_version=5.2.2???
geckolib_fabric_version=5.2.2???
create_neoforge_version=???
create_fabric_version=???
ars_neoforge_version=???
twilightforest_forge_version=???
sewingkit_version=2.7.1
sewingkit_minecraft_version=26.1
more_food_neoforge_version=???
more_food_fabric_version=???
phc_food_core_neoforge_version=???
phc_crops_neoforge_version=???
phc_trees_neoforge_version=???
phc_food_extended_neoforge_version=???
crafttweaker_neoforge_version=???
kubejs_neoforge_version=???
rhino_neoforge_version=???
colorful_hearts_neoforge_version=???
colorful_hearts_fabric_version=???
lmba_neoforge_version=7073238
lmba_fabric_version=7073237
puzzles_lib_neoforge_version=7076802
puzzles_lib_fabric_version=7076801
forge_config_api_fabric_version=7065985
vampirism_neoforge_version=???
fabric_seasons_version=???
fabric_seasons_extras_version=???
ecliptic_neoforge_version=???
# https://www.curseforge.com/minecraft/mc-mods/lets-do-bakery-farm-charm-compat/files/all
letsdo_bakery_neoforge_version=
letsdo_bakery_fabric_version=
# https://www.curseforge.com/minecraft/mc-mods/lets-do-beachparty/files/all
letsdo_beach_neoforge_version=
letsdo_beach_fabric_version=
# https://www.curseforge.com/minecraft/mc-mods/lets-do-bloomingnature/files/all
letsdo_blooming_neoforge_version=
letsdo_blooming_fabric_version=
# https://www.curseforge.com/minecraft/mc-mods/lets-do-brewery-farm-charm-compat/files/all
letsdo_brewery_neoforge_version=
letsdo_brewery_fabric_version=
# https://www.curseforge.com/minecraft/mc-mods/lets-do-candlelight-farm-charm-compat/files/all
letsdo_candlelight_neoforge_version=
letsdo_candlelight_fabric_version=
# https://www.curseforge.com/minecraft/mc-mods/lets-do-herbal-brews/files/all
letsdo_herbal_neoforge_version=
letsdo_herbal_fabric_version=
# https://www.curseforge.com/minecraft/mc-mods/lets-do-meadow/files/all
letsdo_meadow_neoforge_version=
letsdo_meadow_fabric_version=
# https://www.curseforge.com/minecraft/mc-mods/lets-do-farm-charm/files/all
letsdo_farm_neoforge_version=
letsdo_farm_fabric_version=
# https://www.curseforge.com/minecraft/mc-mods/lets-do-vinery/files/all
letsdo_vinery_neoforge_version=
letsdo_vinery_fabric_version=
# https://www.curseforge.com/minecraft/mc-mods/lets-do-wildernature/files/all
letsdo_wilder_neoforge_version=
letsdo_wilder_fabric_version=
# https://www.curseforge.com/minecraft/mc-mods/alloy-forgery/files/all
owo_neoforge=
owo_fabric=
alloy_forgery_neoforge=
alloy_forgery_fabric=

# Mod options
mod_display_name=Homeostatic
mod_name=Homeostatic
mod_id=homeostatic
mod_author=wendall911
mod_credits=ashar42
license=MIT
mod_description=A mod about body temperature and moisture. Achieving homeostasis after a little trial and error.
mod_update_branch=26.1

# CurseForge/Modrinth Options
curseforge_api_key_prop=hscurseApiKey
curseforge_id=634466
curseforge_slug=homeostatic
modrinth_api_key_prop=modrinthKey
modrinth_id=oDobngty
discord_webhook_prop=hsDiscordWebhook
discord_dryrun_webhook_prop=discordDryrunWebhook
release_type=release
release_versions=26.1,26.1.1,26.1.2
