modLoader="javafml"
loaderVersion="${neoforge_loader_version_range}"
license="${license}"
issueTrackerURL="https://github.com/${mod_author}/Homeostatic/issues"
[[mods]]
    modId="${mod_id}"
    version="${version}"
    displayName="${mod_name}"
    displayURL="https://github.com/${mod_author}/${mod_name}"
    logoFile="${mod_id}_icon.png"
    authors="${mod_author}"
    credits="${mod_credits}"
    description='''
    ${mod_description}
    '''
[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="${neoforge_loader_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${neoforge_mc_version_range}"
    ordering="NONE"
    side="BOTH"
