plugins {
    id 'multiloader-loader'
    id 'net.neoforged.moddev'
}

def identifier = "${mod_id}-${minecraft_version}-neoforge"

neoForge {
    version = neoforge_version
    runs {
    }
    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
        }
    }
}

dependencies {
    implementation group: 'technology.roughness.whitenoise', name: "whitenoise-${minecraft_version}-neoforge", version: "${whitenoise_version}"
}

sourceSets.main.resources {
    srcDir 'src/generated/resources'
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            groupId project.group
            artifactId identifier
            version project.version
            // This gives us the built version NeoForge requires
            artifact jar
        }
    }
    repositories {
        if (System.getenv('local_maven') != null) {
            maven {
                url 'file://' + System.getenv('local_maven')
            }
        }
    }
}
