plugins {
    id 'multiloader-loader'
    id 'net.neoforged.moddev'
}

neoForge {
    version = neoforge_version
    parchment {
        minecraftVersion = minecraft_version
        mappingsVersion = mappings_version
    }
    runs {
        configureEach {
            systemProperty('neoforge.enabledGameTestNamespaces', mod_id)
            ideName = "NeoForge ${it.name.capitalize()} (${project.path})" // Unify the run config names with fabric
        }
        client {
            client()
        }
        server {
            server()
        }
        data {
            programArguments.addAll '--mod', project.mod_id, '--all', '--output', file('src/generated/resources/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath()
            data()
        }
    }
    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
        }
    }
}

dependencies {
    implementation group: 'com.github.wendall911.climatesettings', name: "climatesettings-${minecraft_version}-neoforge", version: "${climatesettings_version}"
    jarJar group: 'com.github.wendall911.climatesettings', name: "climatesettings-${minecraft_version}-neoforge", version: "${climatesettings_version}"

    implementation group: 'technology.roughness.whitenoise', name: "whitenoise-${minecraft_version}-neoforge", version: "${whitenoise_version}"
    jarJar group: 'technology.roughness.whitenoise', name: "whitenoise-${minecraft_version}-neoforge", version: "${whitenoise_version}"

    compileOnly "mezz.jei:jei-${minecraft_version}-common-api:${jei_version}"
    implementation "mezz.jei:jei-${minecraft_version}-neoforge:${jei_version}"

    implementation group: 'technology.roughness.handbook', name: "handbook-${minecraft_version}-neoforge", version: "${handbook_version}"
    jarJar group: 'technology.roughness.handbook', name: "handbook-${minecraft_version}-neoforge", version: "${handbook_version}"

    implementation group: 'com.github.wendall911.homeostaticseasons', name: "homeostaticseasons-${minecraft_version}-neoforge", version: "${homeostaticseasons_version}"

    compileOnly "me.shedaniel:RoughlyEnoughItems-neoforge:${rei_version}"
    compileOnly "curse.maven:sereneseasons-291874:${serene_seasons_neoforge_version}"
    compileOnly "curse.maven:glitchcore-955399:${glitch_core_neoforge_version}"
    compileOnly "curse.maven:create-328085:${create_neoforge_version}"
    compileOnly "dev.gigaherz.sewingkit:SewingKit-1.21:${sewingkit_version}"
    compileOnly "curse.maven:vampirism-233029:${vampirism_neoforge_version}"
    compileOnly "curse.maven:ecliptic-1118306:${ecliptic_neoforge_version}"

    if (System.getenv('DATA_GEN') != null) {
        runtimeOnly "curse.maven:create-328085:${create_neoforge_version}"
        runtimeOnly "dev.gigaherz.sewingkit:SewingKit-1.21:${sewingkit_version}"
    }
    else {
        //runtimeOnly "curse.maven:sereneseasons-291874:${serene_seasons_neoforge_version}"
        //runtimeOnly "curse.maven:glitchcore-955399:${glitch_core_neoforge_version}"
        //runtimeOnly "curse.maven:ecliptic-1118306:${ecliptic_neoforge_version}"
        //runtimeOnly "me.shedaniel:RoughlyEnoughItems-neoforge:${rei_version}"
        runtimeOnly "dev.architectury:architectury-neoforge:${architectury_version}"
        //runtimeOnly "me.shedaniel.cloth:cloth-config-neoforge:${cloth_config_version}"
        runtimeOnly "curse.maven:simpletextoverlay-321283:${simpletextoverlay_neoforge_version}"
        //runtimeOnly "dev.gigaherz.sewingkit:SewingKit-${minecraft_version}:${sewingkit_version}"
        //runtimeOnly "curse.maven:configured-457570:4462839"
        //runtimeOnly "curse.maven:biomesoplenty-220318:${bop_neoforge_version}"
        runtimeOnly "curse.maven:terrablender-940057:${terrablender_neoforge_version}"
        runtimeOnly "curse.maven:regions-659110:${regions_neoforge_version}"
        //runtimeOnly "curse.maven:terralith-513688:5512077"
        //runtimeOnly "curse.maven:primalwinter-393321:4575861"
        //runtimeOnly "curse.maven:byg-1070751:${byg_neoforge_version}"
        //runtimeOnly "curse.maven:tyg-962544:${tyg_neoforge_version}"
        //runtimeOnly "curse.maven:corgilib-693313:${corgilib_neoforge_version}"
        //runtimeOnly "software.bernie.geckolib:geckolib-neoforge-${minecraft_version}:${geckolib_neoforge_version}"
        //runtimeOnly "curse.maven:twilightforest-227639:${twilight_forest_neoforge_version}"
        //runtimeOnly "curse.maven:botania-225643:???"
        runtimeOnly "curse.maven:curios-309927:${curios_neoforge_version}"
        //runtimeOnly "curse.maven:croptopia-415438:4512807"
        //runtimeOnly "curse.maven:farmers_delight-398521:???"
        //runtimeOnly "curse.maven:xerca-341575:???"
        //runtimeOnly "curse.maven:morecraft-59648:???"
        //runtimeOnly "curse.maven:sophisticated_core-618298:???"
        //runtimeOnly "curse.maven:sophisticated_backpacks-422301:???"
        //runtimeOnly "curse.maven:ecologics-570463:???"
        //runtimeOnly "curse.maven:sprout-565856:???"
        //runtimeOnly "curse.maven:arsnouveau-401955:${ars_neoforge_version}"
        //runtimeOnly "curse.maven:ars_elemental-561470:5652442"
        //runtimeOnly "curse.maven:create-328085:${create_neoforge_version}"
        //runtimeOnly "curse.maven:create_cafe-542235:???"
        //runtimeOnly "curse.maven:kiwi-303657:???"
        //runtimeOnly "curse.maven:fruittrees-355467:???"
        //runtimeOnly "curse.maven:appleskin-248787:4605078"
        //runtimeOnly "curse.maven:puzzleslib-495476:4660882"
        //runtimeOnly "curse.maven:leavemybarsalone-281715:4613509"
        //runtimeOnly "curse.maven:scuba_gear-399090:4593711"
        //runtimeOnly "curse.maven:kobolds-484967:4632499"
        //runtimeOnly "curse.maven:more_food-874343:${more_food_neoforge_version}"
        //runtimeOnly "curse.maven:kubejs-238086:${kubejs_neoforge_version}"
        //runtimeOnly "curse.maven:rhino-416294:${rhino_neoforge_version}"
        //runtimeOnly "curse.maven:crafttweaker-239197:${crafttweaker_neoforge_version}"
        //runtimeOnly "curse.maven:phc_food_core-372534:${phc_food_core_neoforge_version}"
        //runtimeOnly "curse.maven:phc_crops-361385:${phc_crops_neoforge_version}"
        //runtimeOnly "curse.maven:phc_trees-365460:${phc_trees_neoforge_version}"
        //runtimeOnly "curse.maven:phc_food_extended-402231:${phc_food_extended_neoforge_version}"
        //runtimeOnly "curse.maven:eternal_starlight-1080592:5673629"
        //runtimeOnly "curse.maven:undergarden-379849:5651032"
        //runtimeOnly "curse.maven:colorful_hearts-854213:${colorful_hearts_neoforge_version}"
        //runtimeOnly "curse.maven:puzzles_lib-495476:${puzzles_lib_neoforge_version}"
        //runtimeOnly "curse.maven:lmba-281715:${lmba_neoforge_version}"
        //runtimeOnly "curse.maven:vampirism-233029:${vampirism_neoforge_version}"
        //runtimeOnly "curse.maven:letsdo_bakery-1038130:${letsdo_bakery_neoforge_version}"
        //runtimeOnly "curse.maven:letsdo_beach-858691:${letsdo_beach_neoforge_version}"
        //runtimeOnly "curse.maven:letsdo_blooming-962885:${letsdo_blooming_neoforge_version}"
        //runtimeOnly "curse.maven:letsdo_brewery-1038106:${letsdo_brewery_neoforge_version}"
        //runtimeOnly "curse.maven:letsdo_candlelight-1038117:${letsdo_candlelight_neoforge_version}"
        //runtimeOnly "curse.maven:letsdo_herbal-951221:${letsdo_herbal_neoforge_version}"
        //runtimeOnly "curse.maven:letsdo_meadow-821483:${letsdo_meadow_neoforge_version}"
        //runtimeOnly "curse.maven:letsdo_farm-1038103:${letsdo_farm_neoforge_version}"
        //runtimeOnly "curse.maven:letsdo_vinery-704465:${letsdo_vinery_neoforge_version}"
        //runtimeOnly "curse.maven:letsdo_wilder-1071657:${letsdo_wilder_neoforge_version}"
    }
}

sourceSets.main.resources {
    srcDir 'src/generated/resources'
}

def changelogFile = project(":").projectDir.toString() + '/build/libs/changelog.txt'
def publishFile = project(":").projectDir.toString() + "/NeoForge/build/libs/${archivesBaseName}-${version}.jar"
def display_name = "${project.name} ${minecraft_version}-${version}"
def display_version = "${minecraft_version}-${version}"

publishMods {
    file = file(publishFile)
    if (file(changelogFile).exists()) {
        changelog = file(changelogFile).text
    }
    displayName = "${display_name}"
    version = "${display_version}"
    type = "${release_type}".startsWith("release") ? STABLE : ("${release_type}".startsWith("beta") ? BETA : ALPHA)
    modLoaders.add('neoforge')
    dryRun = providers.environmentVariable('DO_RELEASE').getOrNull() == null

    if (project.hasProperty("${curseforge_api_key_prop}")) {
        curseforge {
            accessToken = project.property("${curseforge_api_key_prop}")
            projectId = "${curseforge_id}"
            projectSlug = "${curseforge_slug}"
            javaVersions.add(JavaVersion.toVersion("${java_version}"))
            clientRequired = true
            serverRequired = true
            minecraftVersions.addAll("${release_versions}".split(','))
            optional('actually-harvest')
            optional('betterdays')
            optional('charged-charms')
            optional('creeper-fireworks')
            optional('magical-psi-revival')
            optional('simpletextoverlay')
            optional('ready-player-fun')
            optional('survivalist-essentials')
            optional('tinkersurvival')
            optional('configured')
            optional('catalogue')
            optional('jei')
            optional('serene-seasons')
            optional('biomes-o-plenty')
            optional('oh-the-biomes-weve-gone')
            optional('croptopia')
            optional('farmers-delight')
            optional('xercamod')
            optional('kitteh6660s-morecraft')
            optional('sophisticated-backpacks')
            optional('ecologics')
            optional('ars-nouveau')
            optional('ars-elemental')
            optional('sprout')
            optional('create-cafe')
            optional('fruit-trees')
            optional('leave-my-bars-alone')
            optional('create')
            optional('scuba-gear')
            optional('kobolds')
            optional('primal-winter')
            optional('tinkers-construct')
            optional('sewing-kit')
            optional('more-food-xd')
            optional('pams-harvestcraft-2-food-core')
            optional('pams-harvestcraft-2-crops')
            optional('pams-harvestcraft-2-trees')
            optional('pams-harvestcraft-2-food-extended')
            optional('eternal-starlight')
            optional('the-undergarden')
            optional('terralith')
            optional('ecliptic-seasons')
            optional('regions-unexplored')
            optional('lets-do-bakery-farm-charm-compat')
            optional('lets-do-brewery-farm-charm-compat')
            optional('lets-do-candlelight-farm-charm-compat')
            optional('lets-do-herbal-brews')
            optional('lets-do-meadow')
            optional('lets-do-farm-charm')
            optional('lets-do-vinery')
        }
    }
    if (project.hasProperty("${modrinth_api_key_prop}")) {
        modrinth {
            accessToken = project.property("${modrinth_api_key_prop}")
            projectId = "${modrinth_id}"
            minecraftVersions.addAll("${release_versions}".split(','))
            optional('actually-harvest')
            optional('betterdays')
            optional('charged-charms')
            optional('creeper-fireworks-mod')
            optional('magical-psi-revival')
            optional('simpletextoverlay')
            optional('ready-player-fun')
            optional('survivalist-essentials')
            optional('tinkersurvival')
            optional('create')
            optional('ecologics')
            optional('create-cafe')
            optional('scuba-gear')
            optional('farmers-delight')
            optional('xercamod')
            optional('leave-my-bars-alone')
            optional('sprout')
            optional('jei')
            optional('oh-the-biomes-weve-gone')
            optional('kobolds')
            optional('primal-winter')
            optional('tinkers-construct')
            optional('fruitful-fun')
            optional('more-food-xd')
            optional('eternal-starlight')
            optional('the-undergarden')
            optional('terralith')
            optional('regions-unexplored')
            optional('lets-do-bakery-farmcharm-compat')
            optional('lets-do-brewery-farmcharm-compat')
            optional('lets-do-candlelight-farmcharm-compat')
            optional('lets-do-herbalbrews')
            optional('lets-do-meadow')
            optional('lets-do-farm-charm')
            optional('lets-do-vinery')
        }
    }
    if (project.hasProperty("${discord_webhook_prop}")) {
        discord {
            webhookUrl = project.property("${discord_webhook_prop}")
            dryRunWebhookUrl = project.property("${discord_dryrun_webhook_prop}")
            username = "${mod_author}"
            content = changelog.map {
                "# A new version of ${mod_display_name} for NeoForge ${minecraft_version} has been released! \n" + it
            }
        }
    }
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            groupId project.group
            artifactId project.archivesBaseName
            version project.version
            // This gives us the built version NeoForge requires
            artifact jar
        }
    }
}
